name: hand-det-recon
channels:
  - menpo
  - defaults
  - conda-forge
dependencies:
  - opencv
  - python=3.7
  - matplotlib
  - numpy
  - pillow
  - trimesh
  - tqdm
  - pip
  - pip:
    - git+https://github.com/hassony2/chumpy.git
    - opencv-python
    - easydict
    - cython
    - msgpack
    - pyyaml 
    - tensorboardX
    - jinja2
    - ray